version: '3.8'

services:
  thalex:
    image: thalex:0.1.0-snapshot
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - 8080:80
    environment:
      - TZ=Asia/Tehran
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
